<link rel="shortcut icon" media="all" href="http://placehold.it/1100x500/f39c12/ffffff&amp;text=Comming+Soon"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/bootstrap/css/bootstrap.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/notify/animate.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/font-awesome-4.5.0/css/font-awesome.min.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/ionicons-master/css/ionicons.min.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/daterangepicker/daterangepicker.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/datatables-2/datatables.net-dt/css/jquery.dataTables.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/datatables-2/datatables.net-bs/css/dataTables.bootstrap.min.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/datatables-2/datatables.net-buttons-bs/css/buttons.bootstrap.min.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/fileinput/css/fileinput.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/dist/css/customLTE.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/dist/css/skins/skin-white.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/slick/slick.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/slick/slick-theme.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/animsition/dist/css/animsition.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/simple-pagination/simplePagination.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/dist/css/vertical-carousel.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/validator/dist/css/bootstrapValidator.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/datepicker/datepicker3.css"/>
<link media="all" type="text/css" rel="stylesheet" href="../adminLTE/plugins/TimeCircles/inc/TimeCircles.css"/>